# Generated by Django 5.1.4 on 2025-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_student_delete_nithin"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.CharField(
                default="https://atlas-content-cdn.pixelsquid.com/stock-images/cartoon-boy-8JY1YDF-600.jpg",
                max_length=1000,
            ),
        ),
    ]
